export const GET_MY_PROFILE = "GET_MY_PROFILE";
export const UPDATE_MY_PROFILE  = "UPDATE_MY_PROFILE";
export const GET_FRIENDS_LIST = "GET_FRIENDS_LIST";
export const GET_ACCEPT_LIST = "GET_ACCEPT_LIST";
export const ACCEPT_FRIEND = "ACCEPT_FRIEND";